
version: '3.8'

services:
  app: # Spring Boot application
    build:
      context: .
      dockerfile: Dockerfile # Build using the Dockerfile in the current directory
    ports:
      - "8080:8080" # Expose the app on port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spring_jenkins
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
     
    depends_on:
      - db # Ensure the database service starts before the app

  db: # MySQL database
    image: mysql:latest # Use the official MySQL 8.0 image
    environment:
      MYSQL_DATABASE: spring_jenkins
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" # Expose MySQL on port 3306
    volumes:
      - db_data:/var/lib/mysql # Persist MySQL data

volumes:
  db_data: # Named volume for MySQL